export const PROFESSIONALS = [
  {
    id: 'p1',
    name: 'Marcus Rivera',
    type: 'Photographer',
    specialization: 'Wedding & Portrait',
    location: 'New York, NY',
    rating: 4.9,
    reviews: 142,
    experience: 8,
    price: 350,
    priceUnit: 'hr',
    verified: true,
    available: true,
    avatar: 'https://images.unsplash.com/photo-1475274226786-e636f48a5645?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1770301312795-abdc6deee5a8?w=800&h=500&fit=crop&auto=format',
    bio: "Wedding and portrait photographer with 8 years of experience capturing life's most precious moments. My style blends documentary authenticity with artistic composition.",
    portfolio: [
      'https://images.unsplash.com/photo-1770301312795-abdc6deee5a8?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1588177364821-2bbfec507203?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1763105358968-fbf009067cda?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1529634897274-69e6ac04f315?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1507095639680-33b1e1a7af05?w=600&h=600&fit=crop&auto=format',
    ],
    services: [
      { id: 's1', name: 'Wedding Full Day', price: 2800, duration: '10 hrs', deliverables: '500+ edited photos', description: 'Complete coverage of your wedding day from prep to reception.' },
      { id: 's2', name: 'Portrait Session', price: 450, duration: '2 hrs', deliverables: '30 edited photos', description: 'Professional portrait shoot in studio or outdoor location.' },
      { id: 's3', name: 'Engagement Shoot', price: 650, duration: '3 hrs', deliverables: '60 edited photos', description: 'Romantic engagement session at a meaningful location.' },
    ],
    tags: ['Wedding', 'Portrait', 'Outdoor'],
  },
  {
    id: 'p2',
    name: 'Sophia Chen',
    type: 'Photographer',
    specialization: 'Fashion & Editorial',
    location: 'Los Angeles, CA',
    rating: 4.8,
    reviews: 89,
    experience: 6,
    price: 420,
    priceUnit: 'hr',
    verified: true,
    available: true,
    avatar: 'https://images.unsplash.com/photo-1512813498716-3e640fed3f39?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1606143412458-acc5f86de897?w=800&h=500&fit=crop&auto=format',
    bio: 'Fashion and editorial photographer based in LA. Worked with top brands and magazines including Vogue, Harper\'s Bazaar, and emerging labels.',
    portfolio: [
      'https://images.unsplash.com/photo-1606143412458-acc5f86de897?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1532170579297-281918c8ae72?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1517462964-21fdcec3f25b?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1581841064838-a470c740e8ee?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1684598273432-8f8e882cd16f?w=600&h=600&fit=crop&auto=format',
    ],
    services: [
      { id: 's4', name: 'Fashion Editorial', price: 1800, duration: '8 hrs', deliverables: '200+ edited photos', description: 'Full editorial shoot with styling direction and post-production.' },
      { id: 's5', name: 'Brand Campaign', price: 3500, duration: '12 hrs', deliverables: '300+ edited photos', description: 'Complete brand campaign photography for commercial use.' },
    ],
    tags: ['Fashion', 'Editorial', 'Commercial'],
  },
  {
    id: 'p3',
    name: 'Alex Thompson',
    type: 'Videographer',
    specialization: 'Cinematic & Documentary',
    location: 'Chicago, IL',
    rating: 4.7,
    reviews: 67,
    experience: 5,
    price: 500,
    priceUnit: 'hr',
    verified: true,
    available: false,
    avatar: 'https://images.unsplash.com/photo-1621024994278-e409544f4085?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1625690303837-654c9666d2d0?w=800&h=500&fit=crop&auto=format',
    bio: 'Cinematic storyteller creating documentary-style films for brands, events, and personal projects. Specializing in emotional narratives.',
    portfolio: [
      'https://images.unsplash.com/photo-1625690303837-654c9666d2d0?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1611784728558-6c7d9b409cdf?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1594394489098-74ac04c0fc2e?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1515634928627-2a4e0dae3ddf?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1553166272-e69910ab5ae1?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1632187981988-40f3cbaeef5e?w=600&h=600&fit=crop&auto=format',
    ],
    services: [
      { id: 's6', name: 'Wedding Film', price: 3200, duration: 'Full day', deliverables: '10-min highlight + raw footage', description: 'Cinematic wedding film capturing every emotion.' },
      { id: 's7', name: 'Corporate Video', price: 2500, duration: '1 day', deliverables: '3-5 min final cut', description: 'Professional corporate videos for internal and external use.' },
    ],
    tags: ['Cinematic', 'Documentary', 'Wedding'],
  },
  {
    id: 'p4',
    name: 'Priya Nair',
    type: 'Photographer',
    specialization: 'Events & Corporate',
    location: 'New York, NY',
    rating: 4.9,
    reviews: 203,
    experience: 10,
    price: 280,
    priceUnit: 'hr',
    verified: true,
    available: true,
    avatar: 'https://images.unsplash.com/photo-1542992933-ce75d0187ec1?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1758613653298-738e98658e31?w=800&h=500&fit=crop&auto=format',
    bio: 'Corporate and events photographer with a decade of experience. Trusted by Fortune 500 companies for conferences, headshots, and product launches.',
    portfolio: [
      'https://images.unsplash.com/photo-1758613653298-738e98658e31?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1758613654216-ea195d4382f7?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1758613654472-7d0f611c1b82?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1758613654757-7c4f113a6782?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1758613654800-26e7f2706fbf?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1758810411741-8062f6597c16?w=600&h=600&fit=crop&auto=format',
    ],
    services: [
      { id: 's8', name: 'Corporate Headshots', price: 800, duration: '4 hrs', deliverables: '20 edited headshots', description: 'Professional headshots for your entire team.' },
      { id: 's9', name: 'Event Coverage', price: 1200, duration: '6 hrs', deliverables: '400+ edited photos', description: 'Comprehensive event photography.' },
    ],
    tags: ['Corporate', 'Events', 'Headshots'],
  },
  {
    id: 'p5',
    name: 'Jordan Mills',
    type: 'Videographer',
    specialization: 'Music & Live Events',
    location: 'Austin, TX',
    rating: 4.6,
    reviews: 54,
    experience: 4,
    price: 380,
    priceUnit: 'hr',
    verified: false,
    available: true,
    avatar: 'https://images.unsplash.com/photo-1611784728558-6c7d9b409cdf?w=200&h=200&fit=crop&auto=format',
    cover: 'https://images.unsplash.com/photo-1594394489098-74ac04c0fc2e?w=800&h=500&fit=crop&auto=format',
    bio: 'Live events and music video specialist based in Austin. Worked with artists and festivals across the US.',
    portfolio: [
      'https://images.unsplash.com/photo-1594394489098-74ac04c0fc2e?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1625690303837-654c9666d2d0?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1553166272-e69910ab5ae1?w=600&h=600&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1515634928627-2a4e0dae3ddf?w=600&h=600&fit=crop&auto=format',
    ],
    services: [
      { id: 's10', name: 'Music Video', price: 2800, duration: '2 days', deliverables: '3-5 min music video', description: 'Professional music video production.' },
    ],
    tags: ['Music', 'Live Events', 'Concert'],
  },
];

export const CATEGORIES = [
  { id: 'wedding', label: 'Wedding', icon: '💍' },
  { id: 'portrait', label: 'Portrait', icon: '🎭' },
  { id: 'event', label: 'Event', icon: '🎉' },
  { id: 'fashion', label: 'Fashion', icon: '👗' },
  { id: 'corporate', label: 'Corporate', icon: '🏢' },
  { id: 'product', label: 'Product', icon: '📦' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'sports', label: 'Sports', icon: '⚡' },
];

export const JOBS = [
  {
    id: 'j1',
    title: 'Wedding Photographer Needed',
    client: 'Emily & David W.',
    clientAvatar: 'https://images.unsplash.com/photo-1532170579297-281918c8ae72?w=100&h=100&fit=crop&auto=format',
    location: 'Brooklyn, NY',
    date: 'Oct 15, 2026',
    budget: '$2,500 – $3,500',
    category: 'Wedding',
    description: 'Looking for an experienced wedding photographer for our intimate outdoor ceremony (80 guests). Ceremony at 4pm, reception until midnight. Need full-day coverage.',
    requirements: ['5+ years experience', 'Second shooter preferred', 'Online gallery delivery', 'Print rights included'],
    applications: 12,
    posted: '2 days ago',
  },
  {
    id: 'j2',
    title: 'Fashion Editorial Shoot',
    client: 'NOVA Magazine',
    clientAvatar: 'https://images.unsplash.com/photo-1606143412458-acc5f86de897?w=100&h=100&fit=crop&auto=format',
    location: 'Manhattan, NY',
    date: 'Sep 28, 2026',
    budget: '$1,800 – $2,400',
    category: 'Fashion',
    description: 'Seeking a fashion photographer for a 6-page editorial spread for our October issue. Theme: "Urban Futurism". Models and stylist provided.',
    requirements: ['Fashion portfolio required', 'Studio lighting proficiency', 'Medium format preferred'],
    applications: 8,
    posted: '5 hours ago',
  },
  {
    id: 'j3',
    title: 'Corporate Headshots — Tech Team',
    client: 'Nexus AI',
    clientAvatar: 'https://images.unsplash.com/photo-1758613654800-26e7f2706fbf?w=100&h=100&fit=crop&auto=format',
    location: 'San Francisco, CA',
    date: 'Sep 22, 2026',
    budget: '$1,200 – $1,600',
    category: 'Corporate',
    description: 'We need professional headshots for our 25-person engineering team. Office location. Same-day editing turnaround preferred.',
    requirements: ['Portable studio setup', 'Same-day or next-day delivery', 'LinkedIn-ready edits'],
    applications: 5,
    posted: '1 day ago',
  },
  {
    id: 'j4',
    title: 'Music Video Videographer',
    client: 'Luna & The Waves',
    clientAvatar: 'https://images.unsplash.com/photo-1542992933-ce75d0187ec1?w=100&h=100&fit=crop&auto=format',
    location: 'Austin, TX',
    date: 'Oct 4, 2026',
    budget: '$2,000 – $3,000',
    category: 'Music',
    description: 'Indie band seeking a videographer for a 2-day music video shoot. Multiple locations including rooftop, studio, and urban settings.',
    requirements: ['Cinematic color grade', 'Drone shots a plus', 'Experience with music content'],
    applications: 19,
    posted: '3 days ago',
  },
  {
    id: 'j5',
    title: 'Product Photography – E-commerce',
    client: 'Bloom Skincare',
    clientAvatar: 'https://images.unsplash.com/photo-1517462964-21fdcec3f25b?w=100&h=100&fit=crop&auto=format',
    location: 'Remote / LA Studio',
    date: 'Sep 30, 2026',
    budget: '$800 – $1,200',
    category: 'Product',
    description: 'E-commerce product photography for 40 skincare SKUs. Clean white background + lifestyle shots. Studio setup required.',
    requirements: ['Product photography portfolio', 'Ghost mannequin capability', 'Photoshop proficiency'],
    applications: 3,
    posted: '6 hours ago',
  },
];

export const MESSAGES = [
  {
    id: 'm1',
    name: 'Marcus Rivera',
    avatar: 'https://images.unsplash.com/photo-1475274226786-e636f48a5645?w=100&h=100&fit=crop&auto=format',
    lastMessage: 'Sure, I\'m available on the 15th. Let me check my calendar.',
    time: '2m ago',
    unread: 3,
    online: true,
  },
  {
    id: 'm2',
    name: 'Sophia Chen',
    avatar: 'https://images.unsplash.com/photo-1512813498716-3e640fed3f39?w=100&h=100&fit=crop&auto=format',
    lastMessage: 'I\'ve sent you the contract. Please review and sign.',
    time: '1h ago',
    unread: 0,
    online: false,
  },
  {
    id: 'm3',
    name: 'Alex Thompson',
    avatar: 'https://images.unsplash.com/photo-1621024994278-e409544f4085?w=100&h=100&fit=crop&auto=format',
    lastMessage: 'The final edit is ready! Check your email.',
    time: '3h ago',
    unread: 1,
    online: true,
  },
  {
    id: 'm4',
    name: 'Priya Nair',
    avatar: 'https://images.unsplash.com/photo-1542992933-ce75d0187ec1?w=100&h=100&fit=crop&auto=format',
    lastMessage: 'Great! Looking forward to working with you.',
    time: 'Yesterday',
    unread: 0,
    online: false,
  },
];

export const CHAT_MESSAGES = [
  { id: 'c1', from: 'them', text: 'Hi! I saw your booking request for the Oct 15 wedding.', time: '10:02 AM' },
  { id: 'c2', from: 'me', text: 'Yes! We\'re so excited. It\'ll be an outdoor ceremony in Brooklyn.', time: '10:04 AM' },
  { id: 'c3', from: 'them', text: 'Beautiful! I love outdoor weddings. How many guests are you expecting?', time: '10:05 AM' },
  { id: 'c4', from: 'me', text: 'Around 80 guests. Ceremony at 4pm, reception until midnight.', time: '10:07 AM' },
  { id: 'c5', from: 'them', text: 'Perfect. I can offer you my Full Day package — that includes 10 hours of coverage, 500+ edited photos, and an online gallery.', time: '10:08 AM' },
  { id: 'c6', from: 'me', text: 'That sounds perfect! What\'s the pricing?', time: '10:10 AM' },
  { id: 'c7', from: 'them', text: 'For full day wedding coverage it\'s $2,800. I also include a complimentary engagement session!', time: '10:11 AM' },
  { id: 'c8', from: 'me', text: 'That\'s great. Can we set up a call to discuss details?', time: '10:14 AM' },
  { id: 'c9', from: 'them', text: 'Sure, I\'m available on the 15th. Let me check my calendar.', time: '10:15 AM' },
];

export const NOTIFICATIONS = [
  { id: 'n1', type: 'booking', icon: '📅', title: 'Booking Confirmed', body: 'Marcus Rivera accepted your booking for Oct 15.', time: '5 min ago', unread: true },
  { id: 'n2', type: 'message', icon: '💬', title: 'New Message', body: 'Sophia Chen: "I\'ve sent you the contract..."', time: '1h ago', unread: true },
  { id: 'n3', type: 'job', icon: '🎯', title: 'New Job Match', body: 'A wedding photography job in Brooklyn matches your profile.', time: '2h ago', unread: true },
  { id: 'n4', type: 'application', icon: '✅', title: 'Application Shortlisted', body: 'NOVA Magazine shortlisted your proposal.', time: '3h ago', unread: false },
  { id: 'n5', type: 'connection', icon: '🤝', title: 'New Connection', body: 'Alex Thompson started following you.', time: 'Yesterday', unread: false },
  { id: 'n6', type: 'profile', icon: '👁', title: 'Profile Viewed', body: '14 people viewed your profile this week.', time: 'Yesterday', unread: false },
  { id: 'n7', type: 'review', icon: '⭐', title: 'New Review', body: 'Emily W. left you a 5-star review!', time: '2 days ago', unread: false },
];

export const BOOKINGS = [
  {
    id: 'b1',
    professional: PROFESSIONALS[0],
    type: 'Wedding Full Day',
    date: 'Oct 15, 2026',
    time: '2:00 PM',
    location: 'Brooklyn Botanic Garden, NY',
    status: 'upcoming',
    amount: 2800,
    paid: 700,
  },
  {
    id: 'b2',
    professional: PROFESSIONALS[1],
    type: 'Fashion Editorial',
    date: 'Sep 28, 2026',
    time: '9:00 AM',
    location: 'Studio 22, Manhattan NY',
    status: 'pending',
    amount: 1800,
    paid: 0,
  },
  {
    id: 'b3',
    professional: PROFESSIONALS[3],
    type: 'Corporate Headshots',
    date: 'Sep 5, 2026',
    time: '10:00 AM',
    location: 'Office HQ, 5th Ave NY',
    status: 'completed',
    amount: 800,
    paid: 800,
  },
  {
    id: 'b4',
    professional: PROFESSIONALS[2],
    type: 'Corporate Video',
    date: 'Aug 12, 2026',
    time: '8:00 AM',
    location: 'Chicago Office',
    status: 'cancelled',
    amount: 2500,
    paid: 0,
  },
];

export const PROJECTS = [
  {
    id: 'pr1',
    title: 'Wedding Photography – October 2026',
    category: 'Wedding',
    date: 'Oct 15, 2026',
    location: 'Brooklyn, NY',
    budget: '$2,500 – $3,500',
    description: 'Looking for an experienced wedding photographer for our outdoor ceremony. 80 guests, full day coverage needed.',
    status: 'active',
    applications: 12,
    posted: '2 days ago',
  },
  {
    id: 'pr2',
    title: 'Brand Video for Product Launch',
    category: 'Corporate',
    date: 'Oct 1, 2026',
    location: 'Manhattan, NY',
    budget: '$3,000 – $4,000',
    description: 'Need a videographer to create a 2-3 minute brand film for our new product launch.',
    status: 'active',
    applications: 7,
    posted: '5 days ago',
  },
];

export const CONNECTIONS = [
  {
    id: 'conn1',
    name: 'Marcus Rivera',
    type: 'Photographer',
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1475274226786-e636f48a5645?w=200&h=200&fit=crop&auto=format',
    mutual: 4,
    following: true,
  },
  {
    id: 'conn2',
    name: 'Sophia Chen',
    type: 'Photographer',
    location: 'Los Angeles, CA',
    avatar: 'https://images.unsplash.com/photo-1512813498716-3e640fed3f39?w=200&h=200&fit=crop&auto=format',
    mutual: 2,
    following: false,
  },
  {
    id: 'conn3',
    name: 'Alex Thompson',
    type: 'Videographer',
    location: 'Chicago, IL',
    avatar: 'https://images.unsplash.com/photo-1621024994278-e409544f4085?w=200&h=200&fit=crop&auto=format',
    mutual: 6,
    following: true,
  },
  {
    id: 'conn4',
    name: 'Priya Nair',
    type: 'Photographer',
    location: 'New York, NY',
    avatar: 'https://images.unsplash.com/photo-1542992933-ce75d0187ec1?w=200&h=200&fit=crop&auto=format',
    mutual: 1,
    following: false,
  },
  {
    id: 'conn5',
    name: 'Jordan Mills',
    type: 'Videographer',
    location: 'Austin, TX',
    avatar: 'https://images.unsplash.com/photo-1611784728558-6c7d9b409cdf?w=200&h=200&fit=crop&auto=format',
    mutual: 3,
    following: true,
  },
];

export const ACTIVITY_FEED = [
  {
    id: 'af1',
    user: { name: 'Marcus Rivera', avatar: 'https://images.unsplash.com/photo-1475274226786-e636f48a5645?w=100&h=100&fit=crop&auto=format', type: 'Photographer' },
    action: 'added new portfolio work',
    image: 'https://images.unsplash.com/photo-1770301312795-abdc6deee5a8?w=600&h=400&fit=crop&auto=format',
    time: '2h ago',
    likes: 48,
    comments: 12,
  },
  {
    id: 'af2',
    user: { name: 'Sophia Chen', avatar: 'https://images.unsplash.com/photo-1512813498716-3e640fed3f39?w=100&h=100&fit=crop&auto=format', type: 'Photographer' },
    action: 'completed a fashion editorial for NOVA Magazine',
    image: 'https://images.unsplash.com/photo-1606143412458-acc5f86de897?w=600&h=400&fit=crop&auto=format',
    time: '5h ago',
    likes: 93,
    comments: 21,
  },
  {
    id: 'af3',
    user: { name: 'Alex Thompson', avatar: 'https://images.unsplash.com/photo-1621024994278-e409544f4085?w=100&h=100&fit=crop&auto=format', type: 'Videographer' },
    action: 'posted a behind-the-scenes clip',
    image: 'https://images.unsplash.com/photo-1625690303837-654c9666d2d0?w=600&h=400&fit=crop&auto=format',
    time: '1d ago',
    likes: 67,
    comments: 9,
  },
];

export const CREATOR_STATS = {
  profileViews: 284,
  profileViewsChange: +18,
  newRequests: 6,
  upcomingBookings: 3,
  totalEarnings: 14600,
  monthEarnings: 3200,
  portfolioViews: 1840,
  rating: 4.9,
  reviews: 142,
  completionRate: 98,
};

export const MY_APPLICATIONS = [
  {
    id: 'ap1',
    job: JOBS[0],
    status: 'shortlisted',
    proposalAmount: 3200,
    submittedAt: '2 days ago',
    message: 'I would love to be part of your special day. With 8 years of wedding photography experience...',
  },
  {
    id: 'ap2',
    job: JOBS[1],
    status: 'applied',
    proposalAmount: 2200,
    submittedAt: '3 days ago',
    message: 'Fashion editorial is my specialty. My work has appeared in several major publications...',
  },
  {
    id: 'ap3',
    job: JOBS[2],
    status: 'accepted',
    proposalAmount: 1400,
    submittedAt: '1 week ago',
    message: 'I have extensive experience with corporate headshots and can deliver same-day...',
  },
  {
    id: 'ap4',
    job: JOBS[3],
    status: 'rejected',
    proposalAmount: 2800,
    submittedAt: '2 weeks ago',
    message: 'Music videos are a passion of mine. I have worked with several indie artists...',
  },
];
